---
shared:
  http_host: <%= ENV['HEROKU_REVIEW_APP'] ? "#{ENV['HEROKU_APP_NAME']}.herokuapp.com" : (ENV['HTTP_HOST'] || 'localhost:3000') %>
  basic_auth_username: <%= ENV['BASIC_AUTH_USERNAME'] %>
  basic_auth_password: <%= ENV['BASIC_AUTH_PASSWORD'] %>

  # AWS
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  aws_secret_access_key: <%= ENV['AWS_ACCESS_SECRET'] %>
  aws_s3_region: <%= ENV['AWS_S3_REGION'] || 'eu-central-1' %>
  aws_s3_bucket: <%= ENV['AWS_BUCKET'] %>

  # Sentry
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  sentry_env: <%= ENV['SENTRY_ENV'].presence || Rails.env %>
  sentry_traces_sample_rate: <%= ENV['SENTRY_TRACES_SAMPLE_RATE'].presence.try(:to_f) || 0.1 %>

development:
  secret_key_base: <<INSERT KEY>>

test:
  secret_key_base: <<INSERT KEY>>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
